import enum


class RoleCode(str, enum.Enum):
    CENTRAL_OFFICER = "ROLE_CENTRAL_OFFICER"
    STATE_OFFICER = "ROLE_STATE_OFFICER"
    DISTRICT_OFFICER = "ROLE_DISTRICT_OFFICER"
    PROJECT_AGENCY = "ROLE_PROJECT_AGENCY"
    FIELD_OFFICER = "ROLE_FIELD_OFFICER"
    SOCIAL_OFFICER = "ROLE_SOCIAL_OFFICER"
    SUPER_ADMIN = "ROLE_SUPER_ADMIN"
    ADMIN = "ROLE_ADMIN"



class ProjectStageCode(str, enum.Enum):
    PROJECT_PROPOSAL = "PROJECT_PROPOSAL"
    INITIAL_SCRUTINY = "INITIAL_SCRUTINY"
    LAND_IDENTIFICATION = "LAND_IDENTIFICATION"
    LAND_VERIFICATION = "LAND_VERIFICATION"
    NOTIFICATION = "NOTIFICATION"
    OBJECTION_HEARING = "OBJECTION_HEARING"
    COMPENSATION_ASSESSMENT = "COMPENSATION_ASSESSMENT"
    AWARD = "AWARD"
    COMPENSATION_DISBURSEMENT = "COMPENSATION_DISBURSEMENT"
    POSSESSION = "POSSESSION"
    R_AND_R = "R_AND_R"
    COMPLETION = "COMPLETION"

    # Compatibility aliases
    SCRUTINY = "INITIAL_SCRUTINY"
    AWARD_DECLARATION = "AWARD"
    REHABILITATION_RESETTLEMENT = "R_AND_R"


class ComplianceStatus(str, enum.Enum):
    ON_TRACK = "ON_TRACK"
    DUE_SOON = "DUE_SOON"
    OVERDUE = "OVERDUE"
    COMPLETED = "COMPLETED"



class StageStatus(str, enum.Enum):
    PENDING = "PENDING"
    IN_PROGRESS = "IN_PROGRESS"
    COMPLETED = "COMPLETED"
    BLOCKED = "BLOCKED"


class TransitionDecision(str, enum.Enum):
    APPROVED = "APPROVED"
    REJECTED = "REJECTED"
    OVERRIDDEN = "OVERRIDDEN"


class TaskStatus(str, enum.Enum):
    PENDING = "PENDING"
    IN_REVIEW = "IN_REVIEW"
    COMPLETED = "COMPLETED"
    REJECTED = "REJECTED"


class TaskPriority(str, enum.Enum):
    NORMAL = "NORMAL"
    HIGH = "HIGH"
    CRITICAL = "CRITICAL"


class LandType(str, enum.Enum):
    AGRICULTURAL_IRRIGATED = "AGRICULTURAL_IRRIGATED"
    AGRICULTURAL_UNIRRIGATED = "AGRICULTURAL_UNIRRIGATED"
    COMMERCIAL = "COMMERCIAL"
    RESIDENTIAL = "RESIDENTIAL"
    GOVERNMENT_WASTE = "GOVERNMENT_WASTE"


class AcquisitionStatus(str, enum.Enum):
    PROPOSED = "PROPOSED"
    VERIFIED = "VERIFIED"
    NOTIFIED_SEC11 = "NOTIFIED_SEC11"
    NOTIFIED_SEC19 = "NOTIFIED_SEC19"
    VALUATION_COMPLETED = "VALUATION_COMPLETED"
    AWARD_PASSED = "AWARD_PASSED"
    DISBURSED = "DISBURSED"
    POSSESSION_TAKEN = "POSSESSION_TAKEN"
    DISPUTED = "DISPUTED"


class SocialCategory(str, enum.Enum):
    GEN = "GEN"
    OBC = "OBC"
    SC = "SC"
    ST = "ST"
    BPL = "BPL"


class NotificationSection(str, enum.Enum):
    SECTION_11_PRELIMINARY = "SECTION_11_PRELIMINARY"
    SECTION_19_DECLARATION = "SECTION_19_DECLARATION"
    SECTION_21_PUBLIC_NOTICE = "SECTION_21_PUBLIC_NOTICE"


class NotificationStatus(str, enum.Enum):
    DRAFT = "DRAFT"
    PUBLISHED = "PUBLISHED"
    EXPIRED = "EXPIRED"
    SUPERSEDED = "SUPERSEDED"


class ObjectionStatus(str, enum.Enum):
    PENDING = "PENDING"
    HEARING_SCHEDULED = "HEARING_SCHEDULED"
    ACCEPTED_MODIFIED = "ACCEPTED_MODIFIED"
    REJECTED = "REJECTED"


class AssessmentStatus(str, enum.Enum):
    DRAFT = "DRAFT"
    UNDER_REVIEW = "UNDER_REVIEW"
    APPROVED = "APPROVED"
    REJECTED = "REJECTED"


class AwardStatus(str, enum.Enum):
    DRAFT = "DRAFT"
    UNDER_REVIEW = "UNDER_REVIEW"
    APPROVED = "APPROVED"
    ISSUED = "ISSUED"
    CHALLENGED = "CHALLENGED"
    CLOSED = "CLOSED"

    # Compatibility aliases
    DECLARED = "ISSUED"
    NOTIFIED_TO_OWNERS = "ISSUED"
    UNDER_DISBURSEMENT = "ISSUED"


class DisbursementStatus(str, enum.Enum):
    PENDING = "PENDING"
    PROCESSING = "PROCESSING"
    DISBURSED = "DISBURSED"
    FAILED = "FAILED"
    ON_HOLD = "ON_HOLD"
    CANCELLED = "CANCELLED"

    # Compatibility aliases
    INITIATED = "PENDING"
    PROCESSING_PFMS = "PROCESSING"
    SUCCESS_CREDITED = "DISBURSED"
    FAILED_BOUNCED = "FAILED"
    HELD_IN_ESCROW = "ON_HOLD"


class PossessionStatus(str, enum.Enum):
    PENDING = "PENDING"
    SCHEDULED = "SCHEDULED"
    TAKEN = "TAKEN"
    DISPUTED = "DISPUTED"
    CANCELLED = "CANCELLED"


class PossessionType(str, enum.Enum):
    SECTION_38_REGULAR = "SECTION_38_REGULAR"
    SECTION_40_URGENCY_CLAUSE = "SECTION_40_URGENCY_CLAUSE"

    # Compatibility alias
    REGULAR_POST_DISBURSEMENT = "SECTION_38_REGULAR"


class FamilyType(str, enum.Enum):
    PAF_AFFECTED_ONLY = "PAF_AFFECTED_ONLY"
    PDF_DISPLACED_REQUIRING_RELOCATION = "PDF_DISPLACED_REQUIRING_RELOCATION"


class RehabStatus(str, enum.Enum):
    SURVEYED = "SURVEYED"
    SCHEME_APPROVED = "SCHEME_APPROVED"
    PLOT_ALLOTTED = "PLOT_ALLOTTED"
    SETTLED = "SETTLED"


class DocumentVerificationStatus(str, enum.Enum):
    PENDING = "PENDING"
    VERIFIED = "VERIFIED"
    REJECTED = "REJECTED"


class AlertSeverity(str, enum.Enum):
    INFO = "INFO"
    WARNING = "WARNING"
    CRITICAL = "CRITICAL"
