"""create_core_phase2_schema

Revision ID: 3974f27fc3ae
Revises: 
Create Date: 2026-09-04 08:50:54.626674

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import geoalchemy2

# revision identifiers, used by Alembic.
revision: str = '3974f27fc3ae'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Ensure PostGIS extension exists
    op.execute("CREATE EXTENSION IF NOT EXISTS postgis;")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('land_owners',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('full_name', sa.String(length=100), nullable=False),
    sa.Column('relative_name', sa.String(length=100), nullable=True),
    sa.Column('aadhaar_hash', sa.String(length=64), nullable=False),
    sa.Column('pan_number', sa.String(length=10), nullable=True),
    sa.Column('bank_account_no', sa.String(length=30), nullable=False),
    sa.Column('bank_ifsc_code', sa.String(length=11), nullable=False),
    sa.Column('bank_name', sa.String(length=100), nullable=False),
    sa.Column('phone_number', sa.String(length=15), nullable=False),
    sa.Column('social_category', sa.String(length=20), nullable=False),
    sa.Column('is_kyc_verified', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_land_owners_aadhaar_hash'), 'land_owners', ['aadhaar_hash'], unique=False)
    op.create_index(op.f('ix_land_owners_full_name'), 'land_owners', ['full_name'], unique=False)
    op.create_table('roles',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_roles_name'), 'roles', ['name'], unique=True)
    op.create_table('states',
    sa.Column('id', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('code', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('districts',
    sa.Column('id', sa.String(length=10), nullable=False),
    sa.Column('state_id', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('lgd_code', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['state_id'], ['states.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_districts_state_id'), 'districts', ['state_id'], unique=False)
    op.create_table('tehsils',
    sa.Column('id', sa.String(length=20), nullable=False),
    sa.Column('district_id', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['district_id'], ['districts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tehsils_district_id'), 'tehsils', ['district_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('role_id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=100), nullable=False),
    sa.Column('designation', sa.String(length=100), nullable=False),
    sa.Column('organization', sa.String(length=100), nullable=False),
    sa.Column('state_id', sa.String(length=10), nullable=True),
    sa.Column('district_id', sa.String(length=10), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['district_id'], ['districts.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.ForeignKeyConstraint(['state_id'], ['states.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_district_id'), 'users', ['district_id'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_role_id'), 'users', ['role_id'], unique=False)
    op.create_index(op.f('ix_users_state_id'), 'users', ['state_id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('audit_logs',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('entity_name', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.String(length=100), nullable=False),
    sa.Column('old_values', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('new_values', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_entity_id'), 'audit_logs', ['entity_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_entity_name'), 'audit_logs', ['entity_name'], unique=False)
    op.create_index(op.f('ix_audit_logs_timestamp'), 'audit_logs', ['timestamp'], unique=False)
    op.create_index(op.f('ix_audit_logs_user_id'), 'audit_logs', ['user_id'], unique=False)
    op.create_table('documents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('document_type', sa.String(length=50), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('file_size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=False),
    sa.Column('sha256_hash', sa.String(length=64), nullable=False),
    sa.Column('uploaded_by_user_id', sa.UUID(), nullable=False),
    sa.Column('verification_status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['uploaded_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_documents_document_type'), 'documents', ['document_type'], unique=False)
    op.create_index(op.f('ix_documents_entity_id'), 'documents', ['entity_id'], unique=False)
    op.create_index(op.f('ix_documents_entity_type'), 'documents', ['entity_type'], unique=False)
    op.create_index(op.f('ix_documents_sha256_hash'), 'documents', ['sha256_hash'], unique=False)
    op.create_index(op.f('ix_documents_uploaded_by_user_id'), 'documents', ['uploaded_by_user_id'], unique=False)
    op.create_index(op.f('ix_documents_verification_status'), 'documents', ['verification_status'], unique=False)
    op.create_table('projects',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_code', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('sponsoring_ministry', sa.String(length=100), nullable=False),
    sa.Column('implementing_agency', sa.String(length=100), nullable=False),
    sa.Column('current_stage', sa.String(length=40), nullable=False),
    sa.Column('primary_district_id', sa.String(length=10), nullable=True),
    sa.Column('total_land_proposed_acres', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('total_land_acquired_acres', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('total_possession_acres', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('estimated_budget_inr_cr', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('compensation_assessed_cr', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('compensation_disbursed_cr', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('total_paf_count', sa.Integer(), nullable=False),
    sa.Column('total_pdf_count', sa.Integer(), nullable=False),
    sa.Column('randr_completion_percent', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('alignment_geojson', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('risk_score', sa.Integer(), nullable=False),
    sa.Column('created_by_user_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['primary_district_id'], ['districts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_projects_created_by_user_id'), 'projects', ['created_by_user_id'], unique=False)
    op.create_index(op.f('ix_projects_current_stage'), 'projects', ['current_stage'], unique=False)
    op.create_index(op.f('ix_projects_primary_district_id'), 'projects', ['primary_district_id'], unique=False)
    op.create_index(op.f('ix_projects_project_code'), 'projects', ['project_code'], unique=True)
    op.create_table('villages',
    sa.Column('id', sa.String(length=20), nullable=False),
    sa.Column('tehsil_id', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('census_code', sa.String(length=20), nullable=True),
    sa.Column('circle_rate_rural_factor', sa.Numeric(precision=4, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tehsil_id'], ['tehsils.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_villages_tehsil_id'), 'villages', ['tehsil_id'], unique=False)
    op.create_table('alerts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=True),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('target_role', sa.String(length=36), nullable=True),
    sa.Column('is_resolved', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_role'], ['roles.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alerts_is_resolved'), 'alerts', ['is_resolved'], unique=False)
    op.create_index(op.f('ix_alerts_project_id'), 'alerts', ['project_id'], unique=False)
    op.create_index(op.f('ix_alerts_severity'), 'alerts', ['severity'], unique=False)
    op.create_index(op.f('ix_alerts_target_role'), 'alerts', ['target_role'], unique=False)
    op.create_table('awards',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('award_number', sa.String(length=100), nullable=False),
    sa.Column('award_date', sa.Date(), nullable=False),
    sa.Column('total_parcels_count', sa.Integer(), nullable=False),
    sa.Column('total_area_acres', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('total_award_amount_inr', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('cala_user_id', sa.UUID(), nullable=False),
    sa.Column('digital_sign_hash', sa.String(length=128), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['cala_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_awards_award_number'), 'awards', ['award_number'], unique=True)
    op.create_index(op.f('ix_awards_cala_user_id'), 'awards', ['cala_user_id'], unique=False)
    op.create_index(op.f('ix_awards_project_id'), 'awards', ['project_id'], unique=False)
    op.create_index(op.f('ix_awards_status'), 'awards', ['status'], unique=False)
    op.create_table('land_parcels',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('village_id', sa.String(length=20), nullable=False),
    sa.Column('khasra_number', sa.String(length=50), nullable=False),
    sa.Column('khata_number', sa.String(length=50), nullable=False),
    sa.Column('total_area_sqm', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('acquired_area_sqm', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('land_type', sa.String(length=30), nullable=False),
    sa.Column('circle_rate_per_sqm', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('market_multiplier', sa.Numeric(precision=4, scale=2), nullable=False),
    sa.Column('acquisition_status', sa.String(length=30), nullable=False),
    sa.Column('geojson_polygon', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('geometry', geoalchemy2.types.Geometry(geometry_type='POLYGON', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('centroid_latitude', sa.Numeric(precision=10, scale=7), nullable=False),
    sa.Column('centroid_longitude', sa.Numeric(precision=10, scale=7), nullable=False),
    sa.Column('is_disputed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['village_id'], ['villages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_land_parcels_acquisition_status'), 'land_parcels', ['acquisition_status'], unique=False)
    op.create_index(op.f('ix_land_parcels_is_disputed'), 'land_parcels', ['is_disputed'], unique=False)
    op.create_index(op.f('ix_land_parcels_khasra_number'), 'land_parcels', ['khasra_number'], unique=False)
    op.create_index(op.f('ix_land_parcels_project_id'), 'land_parcels', ['project_id'], unique=False)
    op.create_index(op.f('ix_land_parcels_village_id'), 'land_parcels', ['village_id'], unique=False)
    op.create_table('notifications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('section_type', sa.String(length=30), nullable=False),
    sa.Column('gazette_notification_no', sa.String(length=100), nullable=False),
    sa.Column('publication_date', sa.Date(), nullable=False),
    sa.Column('objection_deadline_date', sa.Date(), nullable=False),
    sa.Column('gazette_document_id', sa.UUID(), nullable=True),
    sa.Column('issued_by_user_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['gazette_document_id'], ['documents.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['issued_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_gazette_notification_no'), 'notifications', ['gazette_notification_no'], unique=False)
    op.create_index(op.f('ix_notifications_issued_by_user_id'), 'notifications', ['issued_by_user_id'], unique=False)
    op.create_index(op.f('ix_notifications_project_id'), 'notifications', ['project_id'], unique=False)
    op.create_index(op.f('ix_notifications_section_type'), 'notifications', ['section_type'], unique=False)
    op.create_table('project_stages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('stage_code', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sla_deadline_days', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_project_stages_project_id'), 'project_stages', ['project_id'], unique=False)
    op.create_index(op.f('ix_project_stages_stage_code'), 'project_stages', ['stage_code'], unique=False)
    op.create_table('randr_schemes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('scheme_title', sa.String(length=200), nullable=False),
    sa.Column('resettlement_site_name', sa.String(length=200), nullable=False),
    sa.Column('total_plots_planned', sa.Integer(), nullable=False),
    sa.Column('total_plots_allotted', sa.Integer(), nullable=False),
    sa.Column('sanctioned_budget_cr', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('spent_budget_cr', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_randr_schemes_project_id'), 'randr_schemes', ['project_id'], unique=False)
    op.create_table('stage_transition_history',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('from_stage', sa.String(length=50), nullable=False),
    sa.Column('to_stage', sa.String(length=50), nullable=False),
    sa.Column('triggered_by_user_id', sa.UUID(), nullable=False),
    sa.Column('decision', sa.String(length=20), nullable=False),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('snapshot_metrics_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['triggered_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stage_transition_history_project_id'), 'stage_transition_history', ['project_id'], unique=False)
    op.create_index(op.f('ix_stage_transition_history_triggered_by_user_id'), 'stage_transition_history', ['triggered_by_user_id'], unique=False)
    op.create_table('workflow_tasks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('task_type', sa.String(length=50), nullable=False),
    sa.Column('assigned_role', sa.String(length=36), nullable=False),
    sa.Column('assigned_user_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('priority', sa.String(length=20), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('action_url', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['assigned_role'], ['roles.id'], ),
    sa.ForeignKeyConstraint(['assigned_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workflow_tasks_assigned_role'), 'workflow_tasks', ['assigned_role'], unique=False)
    op.create_index(op.f('ix_workflow_tasks_assigned_user_id'), 'workflow_tasks', ['assigned_user_id'], unique=False)
    op.create_index(op.f('ix_workflow_tasks_project_id'), 'workflow_tasks', ['project_id'], unique=False)
    op.create_index(op.f('ix_workflow_tasks_status'), 'workflow_tasks', ['status'], unique=False)
    op.create_table('affected_families',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('scheme_id', sa.UUID(), nullable=False),
    sa.Column('head_of_family_name', sa.String(length=100), nullable=False),
    sa.Column('family_type', sa.String(length=30), nullable=False),
    sa.Column('social_category', sa.String(length=20), nullable=False),
    sa.Column('entitled_plot_sqyd', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('allotted_plot_number', sa.String(length=50), nullable=True),
    sa.Column('subsistence_grant_inr', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('transportation_allowance_inr', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('one_time_resettlement_allowance_inr', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('is_grant_disbursed', sa.Boolean(), nullable=False),
    sa.Column('rehabilitation_status', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['scheme_id'], ['randr_schemes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_affected_families_head_of_family_name'), 'affected_families', ['head_of_family_name'], unique=False)
    op.create_index(op.f('ix_affected_families_rehabilitation_status'), 'affected_families', ['rehabilitation_status'], unique=False)
    op.create_index(op.f('ix_affected_families_scheme_id'), 'affected_families', ['scheme_id'], unique=False)
    op.create_table('compensation_assessments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('parcel_id', sa.UUID(), nullable=False),
    sa.Column('base_land_value_inr', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('multiplier_factor', sa.Numeric(precision=4, scale=2), nullable=False),
    sa.Column('market_value_land_inr', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('assets_value_inr', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('solatium_inr', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('additional_market_value_inr', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('total_compensation_inr', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('is_approved_by_cala', sa.Boolean(), nullable=False),
    sa.Column('approval_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['parcel_id'], ['land_parcels.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_compensation_assessments_parcel_id'), 'compensation_assessments', ['parcel_id'], unique=True)
    op.create_table('disbursements',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('award_id', sa.UUID(), nullable=False),
    sa.Column('parcel_id', sa.UUID(), nullable=False),
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('amount_inr', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('pfms_batch_reference', sa.String(length=100), nullable=False),
    sa.Column('payment_status', sa.String(length=20), nullable=False),
    sa.Column('bank_utr_number', sa.String(length=50), nullable=True),
    sa.Column('disbursed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('failure_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['award_id'], ['awards.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['owner_id'], ['land_owners.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['parcel_id'], ['land_parcels.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_disbursements_award_id'), 'disbursements', ['award_id'], unique=False)
    op.create_index(op.f('ix_disbursements_bank_utr_number'), 'disbursements', ['bank_utr_number'], unique=False)
    op.create_index(op.f('ix_disbursements_owner_id'), 'disbursements', ['owner_id'], unique=False)
    op.create_index(op.f('ix_disbursements_parcel_id'), 'disbursements', ['parcel_id'], unique=False)
    op.create_index(op.f('ix_disbursements_payment_status'), 'disbursements', ['payment_status'], unique=False)
    op.create_index(op.f('ix_disbursements_pfms_batch_reference'), 'disbursements', ['pfms_batch_reference'], unique=False)
    op.create_table('field_verifications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('parcel_id', sa.UUID(), nullable=False),
    sa.Column('verified_by_user_id', sa.UUID(), nullable=False),
    sa.Column('verification_date', sa.Date(), nullable=False),
    sa.Column('ground_survey_notes', sa.Text(), nullable=True),
    sa.Column('trees_count', sa.Integer(), nullable=False),
    sa.Column('structures_count', sa.Integer(), nullable=False),
    sa.Column('wells_count', sa.Integer(), nullable=False),
    sa.Column('verification_status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['parcel_id'], ['land_parcels.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['verified_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_field_verifications_parcel_id'), 'field_verifications', ['parcel_id'], unique=False)
    op.create_index(op.f('ix_field_verifications_verified_by_user_id'), 'field_verifications', ['verified_by_user_id'], unique=False)
    op.create_table('objections_claims',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('notification_id', sa.UUID(), nullable=False),
    sa.Column('parcel_id', sa.UUID(), nullable=True),
    sa.Column('owner_id', sa.UUID(), nullable=True),
    sa.Column('objection_type', sa.String(length=50), nullable=False),
    sa.Column('summary_text', sa.Text(), nullable=False),
    sa.Column('hearing_date', sa.Date(), nullable=True),
    sa.Column('disposal_status', sa.String(length=20), nullable=False),
    sa.Column('cala_order_notes', sa.Text(), nullable=True),
    sa.Column('order_document_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['notification_id'], ['notifications.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['order_document_id'], ['documents.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['owner_id'], ['land_owners.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['parcel_id'], ['land_parcels.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_objections_claims_disposal_status'), 'objections_claims', ['disposal_status'], unique=False)
    op.create_index(op.f('ix_objections_claims_notification_id'), 'objections_claims', ['notification_id'], unique=False)
    op.create_index(op.f('ix_objections_claims_owner_id'), 'objections_claims', ['owner_id'], unique=False)
    op.create_index(op.f('ix_objections_claims_parcel_id'), 'objections_claims', ['parcel_id'], unique=False)
    op.create_table('parcel_ownerships',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('parcel_id', sa.UUID(), nullable=False),
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('ownership_share_percent', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('extent_area_sqm', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('mutation_date', sa.Date(), nullable=True),
    sa.Column('is_primary_contact', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['land_owners.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parcel_id'], ['land_parcels.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_parcel_ownerships_owner_id'), 'parcel_ownerships', ['owner_id'], unique=False)
    op.create_index(op.f('ix_parcel_ownerships_parcel_id'), 'parcel_ownerships', ['parcel_id'], unique=False)
    op.create_table('possessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('parcel_id', sa.UUID(), nullable=False),
    sa.Column('possession_date', sa.Date(), nullable=False),
    sa.Column('possession_type', sa.String(length=30), nullable=False),
    sa.Column('is_encumbrance_free', sa.Boolean(), nullable=False),
    sa.Column('possession_certificate_doc_id', sa.UUID(), nullable=True),
    sa.Column('taken_by_agency_officer_id', sa.UUID(), nullable=False),
    sa.Column('handed_over_by_cala_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['handed_over_by_cala_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['parcel_id'], ['land_parcels.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['possession_certificate_doc_id'], ['documents.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['taken_by_agency_officer_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_possessions_handed_over_by_cala_id'), 'possessions', ['handed_over_by_cala_id'], unique=False)
    op.create_index(op.f('ix_possessions_parcel_id'), 'possessions', ['parcel_id'], unique=True)
    op.create_index(op.f('ix_possessions_project_id'), 'possessions', ['project_id'], unique=False)
    op.create_index(op.f('ix_possessions_taken_by_agency_officer_id'), 'possessions', ['taken_by_agency_officer_id'], unique=False)
    op.create_table('asset_valuations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('assessment_id', sa.UUID(), nullable=False),
    sa.Column('asset_category', sa.String(length=30), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('unit', sa.String(length=20), nullable=False),
    sa.Column('unit_rate_inr', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('total_asset_value_inr', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('depreciation_inr', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('net_asset_value_inr', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['assessment_id'], ['compensation_assessments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_asset_valuations_assessment_id'), 'asset_valuations', ['assessment_id'], unique=False)
    op.create_table('randr_allotments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('family_id', sa.UUID(), nullable=False),
    sa.Column('allotment_type', sa.String(length=50), nullable=False),
    sa.Column('asset_identifier', sa.String(length=100), nullable=False),
    sa.Column('allotment_order_no', sa.String(length=100), nullable=False),
    sa.Column('allotment_date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['family_id'], ['affected_families.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_randr_allotments_family_id'), 'randr_allotments', ['family_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_randr_allotments_family_id'), table_name='randr_allotments')
    op.drop_table('randr_allotments')
    op.drop_index(op.f('ix_asset_valuations_assessment_id'), table_name='asset_valuations')
    op.drop_table('asset_valuations')
    op.drop_index(op.f('ix_possessions_taken_by_agency_officer_id'), table_name='possessions')
    op.drop_index(op.f('ix_possessions_project_id'), table_name='possessions')
    op.drop_index(op.f('ix_possessions_parcel_id'), table_name='possessions')
    op.drop_index(op.f('ix_possessions_handed_over_by_cala_id'), table_name='possessions')
    op.drop_table('possessions')
    op.drop_index(op.f('ix_parcel_ownerships_parcel_id'), table_name='parcel_ownerships')
    op.drop_index(op.f('ix_parcel_ownerships_owner_id'), table_name='parcel_ownerships')
    op.drop_table('parcel_ownerships')
    op.drop_index(op.f('ix_objections_claims_parcel_id'), table_name='objections_claims')
    op.drop_index(op.f('ix_objections_claims_owner_id'), table_name='objections_claims')
    op.drop_index(op.f('ix_objections_claims_notification_id'), table_name='objections_claims')
    op.drop_index(op.f('ix_objections_claims_disposal_status'), table_name='objections_claims')
    op.drop_table('objections_claims')
    op.drop_index(op.f('ix_field_verifications_verified_by_user_id'), table_name='field_verifications')
    op.drop_index(op.f('ix_field_verifications_parcel_id'), table_name='field_verifications')
    op.drop_table('field_verifications')
    op.drop_index(op.f('ix_disbursements_pfms_batch_reference'), table_name='disbursements')
    op.drop_index(op.f('ix_disbursements_payment_status'), table_name='disbursements')
    op.drop_index(op.f('ix_disbursements_parcel_id'), table_name='disbursements')
    op.drop_index(op.f('ix_disbursements_owner_id'), table_name='disbursements')
    op.drop_index(op.f('ix_disbursements_bank_utr_number'), table_name='disbursements')
    op.drop_index(op.f('ix_disbursements_award_id'), table_name='disbursements')
    op.drop_table('disbursements')
    op.drop_index(op.f('ix_compensation_assessments_parcel_id'), table_name='compensation_assessments')
    op.drop_table('compensation_assessments')
    op.drop_index(op.f('ix_affected_families_scheme_id'), table_name='affected_families')
    op.drop_index(op.f('ix_affected_families_rehabilitation_status'), table_name='affected_families')
    op.drop_index(op.f('ix_affected_families_head_of_family_name'), table_name='affected_families')
    op.drop_table('affected_families')
    op.drop_index(op.f('ix_workflow_tasks_status'), table_name='workflow_tasks')
    op.drop_index(op.f('ix_workflow_tasks_project_id'), table_name='workflow_tasks')
    op.drop_index(op.f('ix_workflow_tasks_assigned_user_id'), table_name='workflow_tasks')
    op.drop_index(op.f('ix_workflow_tasks_assigned_role'), table_name='workflow_tasks')
    op.drop_table('workflow_tasks')
    op.drop_index(op.f('ix_stage_transition_history_triggered_by_user_id'), table_name='stage_transition_history')
    op.drop_index(op.f('ix_stage_transition_history_project_id'), table_name='stage_transition_history')
    op.drop_table('stage_transition_history')
    op.drop_index(op.f('ix_randr_schemes_project_id'), table_name='randr_schemes')
    op.drop_table('randr_schemes')
    op.drop_index(op.f('ix_project_stages_stage_code'), table_name='project_stages')
    op.drop_index(op.f('ix_project_stages_project_id'), table_name='project_stages')
    op.drop_table('project_stages')
    op.drop_index(op.f('ix_notifications_section_type'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_project_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_issued_by_user_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_gazette_notification_no'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_land_parcels_village_id'), table_name='land_parcels')
    op.drop_index(op.f('ix_land_parcels_project_id'), table_name='land_parcels')
    op.drop_index(op.f('ix_land_parcels_khasra_number'), table_name='land_parcels')
    op.drop_index(op.f('ix_land_parcels_is_disputed'), table_name='land_parcels')
    op.drop_index(op.f('ix_land_parcels_acquisition_status'), table_name='land_parcels')
    op.drop_index('idx_land_parcels_geometry', table_name='land_parcels', postgresql_using='gist')
    op.drop_table('land_parcels')
    op.drop_index(op.f('ix_awards_status'), table_name='awards')
    op.drop_index(op.f('ix_awards_project_id'), table_name='awards')
    op.drop_index(op.f('ix_awards_cala_user_id'), table_name='awards')
    op.drop_index(op.f('ix_awards_award_number'), table_name='awards')
    op.drop_table('awards')
    op.drop_index(op.f('ix_alerts_target_role'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_severity'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_project_id'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_is_resolved'), table_name='alerts')
    op.drop_table('alerts')
    op.drop_index(op.f('ix_villages_tehsil_id'), table_name='villages')
    op.drop_table('villages')
    op.drop_index(op.f('ix_projects_project_code'), table_name='projects')
    op.drop_index(op.f('ix_projects_primary_district_id'), table_name='projects')
    op.drop_index(op.f('ix_projects_current_stage'), table_name='projects')
    op.drop_index(op.f('ix_projects_created_by_user_id'), table_name='projects')
    op.drop_table('projects')
    op.drop_index(op.f('ix_documents_verification_status'), table_name='documents')
    op.drop_index(op.f('ix_documents_uploaded_by_user_id'), table_name='documents')
    op.drop_index(op.f('ix_documents_sha256_hash'), table_name='documents')
    op.drop_index(op.f('ix_documents_entity_type'), table_name='documents')
    op.drop_index(op.f('ix_documents_entity_id'), table_name='documents')
    op.drop_index(op.f('ix_documents_document_type'), table_name='documents')
    op.drop_table('documents')
    op.drop_index(op.f('ix_audit_logs_user_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_timestamp'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_entity_name'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_entity_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_state_id'), table_name='users')
    op.drop_index(op.f('ix_users_role_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_district_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_tehsils_district_id'), table_name='tehsils')
    op.drop_table('tehsils')
    op.drop_index(op.f('ix_districts_state_id'), table_name='districts')
    op.drop_table('districts')
    op.drop_table('states')
    op.drop_index(op.f('ix_roles_name'), table_name='roles')
    op.drop_table('roles')
    op.drop_index(op.f('ix_land_owners_full_name'), table_name='land_owners')
    op.drop_index(op.f('ix_land_owners_aadhaar_hash'), table_name='land_owners')
    op.drop_table('land_owners')
    # ### end Alembic commands ###
